export const groupMap = new Map<RegExp, string>();

groupMap.set(/DMHY/gi, "動漫花園");
groupMap.set(/SHIGURE/gi, "時雨初空");
groupMap.set(/HYSUB/gi, "幻樱字幕组");
groupMap.set(/BeanSub/gi, "豌豆字幕组");
groupMap.set(/FZSD/gi, "风之圣殿");
groupMap.set(/FLsonw|FLsnow/gi, "雪飘工作室");
groupMap.set(/WMSUB/gi, "风车字幕组");
groupMap.set(/DBD-Raws/gi, "DBD 制作组");
groupMap.set(/(\[|)UHA-WING(S|)/gi, "悠哈璃羽字幕社");
groupMap.set(/SweetSub/gi, "SweetSub 字幕组");
groupMap.set(/MMSUB/gi, "MMSUB");
groupMap.set(/LoliHouse/gi, "LoliHouse 压制组");
groupMap.set(/SFEO-Raws/gi, "SFEO-Raws 压制组");
groupMap.set(/SumiSora/gi, "澄空学园");
groupMap.set(/YUI-7/gi, "西农YUI汉化组");
groupMap.set(/Skymoon-Raws/gi, "天月動漫&發佈組");
groupMap.set(/PCSUB/gi, "波洛咖啡厅");
groupMap.set(/Kamigami/gi, "诸神字幕组");
groupMap.set(/Mabors( |-|){0,1}(|Sub)+/gi, "幻之字幕组");
groupMap.set(/DHR\ feat\.nobady98|DHR/gi, "DHR动研字幕组");
groupMap.set(/DMG/gi, "动漫国字幕组");
groupMap.set(/FZsub/gi, "F宅字幕组");
groupMap.set(/Xrip/gi, "Xrip 压制组");
groupMap.set(/A\.I\.R\.nesSub/gi, "A.I.R.nesSub 字幕组");
groupMap.set(/NC-Raws|まひろ🍥|神楽坂 まひろ|推しの子/gi, "NC-Raws 搬运组");
groupMap.set(/NaN-Raws/gi, "NaN-Raws 搬运组");
groupMap.set(/Lilith-Raws/gi, "Lilith-Raws 搬运组");
groupMap.set(/云光字幕组/gi, "云光字幕组");
groupMap.set(/CASO/gi, "华盟字幕组");
groupMap.set(/Comicat(|Sub)+/gi, "漫猫字幕组");
groupMap.set(/KissSub/gi, "爱恋字幕组");
groupMap.set(/JYFanSub|KTXP|JYSUB|JYFANSUB/gi, "极影字幕社");
groupMap.set(/Nekomoe\ (kissaten|kissatten)|Nekomoenai\.sub/gi, "喵萌奶茶屋");
groupMap.set(/Mmch\.sub/gi, "喵萌茶会字幕组");
groupMap.set(/SakuratoSub|sakurato\.sub|Sakurato/gi, "桜都字幕组");
groupMap.set(/STYHSub/gi, "霜庭云花字幕组");
groupMap.set(/Airota-Anonymous|Airota|Ariota/gi, "千夏字幕组");
groupMap.set(/SZW/gi, "森之屋动漫");
groupMap.set(/SAIO-Raws/gi, "SAIO-Raws 压制组");
groupMap.set(/VCB-Studio|VCB-S/gi, "VCB-Studio 压制组");
groupMap.set(/熔岩番剧库|LavaAnimeLib/gi, "熔岩番剧库压制");
groupMap.set(/异域-11番小队/gi, "异域-11番小队");
groupMap.set(/XKSub/gi, "星空字幕组");
groupMap.set(/ZeroSub/gi, "ZeroSub");
groupMap.set(/CoolComic404/gi, "酷漫404");
groupMap.set(/orion origin/gi, "猎户不鸽发布组");
groupMap.set(/MCE/gi, "MCE 汉化组");
groupMap.set(/LavaAnime/gi, "熔岩动画");
groupMap.set(/igsub/gi, "爱咕字幕组");
groupMap.set(/GST/gi, "GST 搬运组");
groupMap.set(/LxyLab/gi, "LxyLab 字幕组");
groupMap.set(/LKSUB/gi, "轻之国度字幕组");
groupMap.set(/Henshin/gi, "Henshin 压制组");
groupMap.set(/LPSub/gi, "离谱Sub");
groupMap.set(/(MingYSub|MingY)/gi, "MingYSub");
groupMap.set(/WOLF|WOLF字幕组\&RH/gi, "WOLF 字幕组");
groupMap.set(/Hakugetsu/gi, "白月字幕组");
groupMap.set(/夏沐字幕组/gi, "夏沐字幕组");
groupMap.set(/KyokuSai/gi, "极彩字幕组");
groupMap.set(/Meowskers/gi, "喵鲁字幕组");
groupMap.set(/Amor字幕组/gi, "Amor 字幕组");
groupMap.set(/POPGO/gi, "漫游字幕组");
groupMap.set(/Moozzi2/gi, "Moozzi2 压制组");
groupMap.set(/mawen1250/gi, "mawen1250 压制组");
groupMap.set(/ANK-Raws|ANK/gi, "ANK-Raws 压制组");
groupMap.set(/Snow-Raws/gi, "花園壓制組");
groupMap.set(/Haruhana/gi, "拨雪寻春字幕组");
groupMap.set(/RATH/gi, "拉斯观测组");
groupMap.set(/SBSUB/gi, "银色子弹字幕组");
groupMap.set(/织梦字幕组/gi, "织梦字幕组");
groupMap.set(/Billion Meta Lab/gi, "亿次研同好会");
groupMap.set(/LavaAnimeSub/gi, "熔岩动画Sub");
groupMap.set(/Kitaujisub/gi, "北宇治字幕组");
groupMap.set(/RHD/gi, "RHD字幕组");
groupMap.set(/CE/gi, "CE家族社");
groupMap.set(/MakariHoshiyume|MakariTsukiyo|Makari/gi, "茉语星梦");
groupMap.set(/HYO/gi, "花園舊社");
groupMap.set(/HaSub/gi, "花语字幕组");
groupMap.set(/Haretahoo/gi, "Haretahoo 字幕组");
groupMap.set(/SGS/gi, "SGS曙光社");
groupMap.set(/LF2/gi, "✿小花花同盟戰線✿");
groupMap.set(/HKG/gi, "HKG字幕組");
groupMap.set(/I\.G/gi, "元古I.G部落");
groupMap.set(/JOJO/gi, "JOJO的奇妙冒险吧");
groupMap.set(/TSDM/gi, "天使动漫自购 / TSDM 字幕组");
groupMap.set(/Romanticat/gi, "猫恋汉化组");
groupMap.set(/FreeSub/gi, "自由字幕组");
groupMap.set(/ACG7/gi, "雷姆利亚");
groupMap.set(/Lamune/gi, "波子汽水汉化组");
groupMap.set(/SC-OL/gi, "雪酷字幕组");
groupMap.set(/AcgmTHK|TUcaptions(|\(THK\))+/gi, "TUcaptions 字幕社");
groupMap.set(/EMD/gi, "恶魔岛字幕组");
groupMap.set(/NTR/gi, "NTR字幕组");
groupMap.set(/TSRJ/gi, "間人字幕組");
groupMap.set(/STK/gi, "生徒会字幕组");
groupMap.set(/Shirokoi/gi, "白恋动漫萝卜部");
groupMap.set(/DHR-Raws/gi, "DHR动研压制组");
groupMap.set(/DHRx幻之/gi, "DHR动研字幕组&幻之字幕组");
groupMap.set(/Dymy/gi, "Dymy字幕組");
groupMap.set(/7³ACG/gi, "7³ACG压制组");
groupMap.set(/Ohys-Raws/gi, "Ohys-Raws 搬运组");
groupMap.set(/Leopard-Raws/gi, "Leopard-Raws 搬运组");
