export const broadcastChannelMap = new Map<RegExp, string>();

broadcastChannelMap.set(/\b(TVRip|TV-Rip|TV|HDTV)\b/gi, "TV OnAir Source");
broadcastChannelMap.set(/\b(WEBRip|WEB-DL|WEB|DL)\b/gi, "Web Download Source");
broadcastChannelMap.set(/\b(BDRip|BD-Rip|BD)\b/gi, "BD Source");
broadcastChannelMap.set(/\b(DVDRip|DVD-Rip|DVD)\b/gi, "DVD Source");
broadcastChannelMap.set(/\b(ATX|AT-X)\b/gi, "AT-X TV");
broadcastChannelMap.set(/\b(NTV)\b/gi, "NTV TV");
broadcastChannelMap.set(/\b(BS11)\b/gi, "BS11 TV");
broadcastChannelMap.set(/\b(WOWOW)\b/gi, "WOWOW TV");
broadcastChannelMap.set(/\b(MX)\b/gi, "TOKYO MX TV");
broadcastChannelMap.set(/\b(BSFUJI)\b/gi, "BS Fuji TV");
broadcastChannelMap.set(/\b(TBS)\b/gi, "TBS TV");
broadcastChannelMap.set(/\b(ABC)\b/gi, "ABC TV");
broadcastChannelMap.set(/\b(BSN)\b/gi, "BSN TV");
broadcastChannelMap.set(/\b(YTV)\b/gi, "YTV Canada TV");
broadcastChannelMap.set(/\b(CX)\b/gi, "Fuji TV");
broadcastChannelMap.set(/\b(NHKG|NHK-G)\b/gi, "NHK-G TV");
broadcastChannelMap.set(/\b(TX)\b/gi, "TV-Tokyo");
broadcastChannelMap.set(/\b(BSJ)\b/gi, "BS TV-Tokyo");
broadcastChannelMap.set(/\b(MBS)\b/gi, "MBS TV");
broadcastChannelMap.set(/\b(Baha)\b/gi, "巴哈姆特動畫瘋");
broadcastChannelMap.set(/\b(B-Global)\b/gi, "BiliBili Global");
broadcastChannelMap.set(/\b(CR)\b/gi, "Crunchyroll");
broadcastChannelMap.set(/\b(Sentai)\b/gi, "Hidive");
broadcastChannelMap.set(/\b(BiliBili|BL)\b/gi, "BiliBili");
broadcastChannelMap.set(/\b(Acfun|AC)\b/gi, "Acfun");
broadcastChannelMap.set(/\b(netflix|NF)\b/gi, "Netflix");

export const mediaTypeMap = new Map<RegExp, string>();

mediaTypeMap.set(/\b(SP)\b/gi, "SP");
mediaTypeMap.set(/\b(OVA)\b/gi, "OVA");
mediaTypeMap.set(/\b(OAD)\b/gi, "OAD");
mediaTypeMap.set(/\b(Movie)\b/gi, "Movie");
mediaTypeMap.set(/\b(Subtitles|Subtitle|Subs)\b/gi, "Subtitles");
mediaTypeMap.set(/\b(Fonts|Font)\b/gi, "Fonts");
mediaTypeMap.set(/\b(NCOP)\b/gi, "Non-Credit Opening");
mediaTypeMap.set(/\b(NCOP1)\b/gi, "Non-Credit Opening 1");
mediaTypeMap.set(/\b(NCOP2)\b/gi, "Non-Credit Opening 2");
mediaTypeMap.set(/\b(NCOP3)\b/gi, "Non-Credit Opening 3");
mediaTypeMap.set(/\b(NCOP4)\b/gi, "Non-Credit Opening 4");
mediaTypeMap.set(/\b(NCOP5)\b/gi, "Non-Credit Opening 5");
mediaTypeMap.set(/\b(NCOP6)\b/gi, "Non-Credit Opening 6");
mediaTypeMap.set(/\b(NCOP7)\b/gi, "Non-Credit Opening 7");
mediaTypeMap.set(/\b(NCOP8)\b/gi, "Non-Credit Opening 8");
mediaTypeMap.set(/\b(NCOP9)\b/gi, "Non-Credit Opening 9");
mediaTypeMap.set(/\b(NCOP10)\b/gi, "Non-Credit Opening 10");
mediaTypeMap.set(/\b(NCOP11)\b/gi, "Non-Credit Opening 11");
mediaTypeMap.set(/\b(NCOP12)\b/gi, "Non-Credit Opening 12");
mediaTypeMap.set(/\b(NCOP13)\b/gi, "Non-Credit Opening 13");
mediaTypeMap.set(/\b(NCOP14)\b/gi, "Non-Credit Opening 14");
mediaTypeMap.set(/\b(NCED)\b/gi, "Non-Credit Ending");
mediaTypeMap.set(/\b(NCED1)\b/gi, "Non-Credit Ending 1");
mediaTypeMap.set(/\b(NCED2)\b/gi, "Non-Credit Ending 2");
mediaTypeMap.set(/\b(NCED3)\b/gi, "Non-Credit Ending 3");
mediaTypeMap.set(/\b(NCED4)\b/gi, "Non-Credit Ending 4");
mediaTypeMap.set(/\b(NCED5)\b/gi, "Non-Credit Ending 5");
mediaTypeMap.set(/\b(NCED6)\b/gi, "Non-Credit Ending 6");
mediaTypeMap.set(/\b(NCED7)\b/gi, "Non-Credit Ending 7");
mediaTypeMap.set(/\b(NCED8)\b/gi, "Non-Credit Ending 8");
mediaTypeMap.set(/\b(NCED9)\b/gi, "Non-Credit Ending 9");
mediaTypeMap.set(/\b(NCED10)\b/gi, "Non-Credit Ending 10");
mediaTypeMap.set(/\b(NCED11)\b/gi, "Non-Credit Ending 11");
mediaTypeMap.set(/\b(NCED12)\b/gi, "Non-Credit Ending 12");
mediaTypeMap.set(/\b(NCED13)\b/gi, "Non-Credit Ending 13");
mediaTypeMap.set(/\b(NCED14)\b/gi, "Non-Credit Ending 14");
